### PR TITLE
Fix directives representation

### PR DESCRIPTION
**Pull request by jmm**
Fix https://github.com/babel/babel-eslint/issues/228.

### CODE REVIEW

**Comment by hzoo** [comment]
I don't think anyone is using this package - we should probably just move it back into babel-eslint or something since it's kind of annoying (although npm link helps)

**Comment by jmm** [comment]
@hzoo You'd have a better read on that than me. Does look like it has at least one "third party" [dependent](https://www.npmjs.com/browse/depended/acorn-to-esprima) though: [esformatter](https://www.npmjs.com/package/esformatter). I guess I could see people being interested in a general purpose Babel AST => ESTree transformer, if such a thing is doable, but another thing is the package name is now a misnomer. So if people were looking for that it might not be as discoverable as it could be.

That's what I've been doing -- `npm link`. Like you said it's a bit annoying, but doable.

**Comment by hzoo** [comment]
Ok that is surprising. https://github.com/millermedeiros/esformatter/commit/c77d9942ca2fe7d1b954dad109ebe9601022484d was 2 days ago. It's a patch to use babylon + https://github.com/babel/babel-eslint/blob/master/index.js#L372-L439

**Comment by jmm** [comment]
> Ok that is surprising. millermedeiros/esformatter@c77d994 was 2 days ago.

Oh, interesting, I had no idea it just started depending on it.

> It's a patch to use babylon + https://github.com/babel/babel-eslint/blob/master/index.js#L372-L439

I wasn't sure what you meant at first, but yeah, looks like that was extracted.

**Pull request merged**
